language: go
go:
 - 1.4
 - release

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

script:
  - go test -v ./...
  - $HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN
